### ISSUE TITLE
🐛 [Bug] Some Suggestions

### ISSUE THREAD

**Issue by hwbrzzl** [goravel/cloudinary#1]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [X] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.18.x

### Goravel Version (Goravel 版本)

1.12.6

### Describe The Problem (描述问题)

1. Optimize README

<img width="849" alt="image" src="https://github.com/goravel/cloudinary/assets/24771476/4225a162-50b9-4b70-b2f3-84a7eac76a4d">

1.1 `cloudinaryFacades "github.com/goravel/cloudinary"` -> `cloudinaryfacades "github.com/goravel/cloudinary/facades"`
1.2 Optimize configuration like other storage packages;

<img width="724" alt="image" src="https://github.com/goravel/cloudinary/assets/24771476/db620099-136c-406f-ba65-1a754c3b9965">

2. The `config/cloudinary.go` and `contracts/cloudinary.go` files seem unnecessary;
3. Please add the LICENSE file;
4. Order import for the `cloudinary.go` file;
5. I think `AllDirectories` and `getAllDirectoriesRecursively` can be merged, `AllDirectories` is very simple, it's unnecessary to separate them;
6. [This line](https://github.com/goravel/cloudinary/blob/b7c0c09cfd137a1d1230e5748723766350bf1ab1/cloudinary.go#L69) is so strange, I suggest optimize it;
7. Does `AssetType` must be set in [this line](https://github.com/goravel/cloudinary/blob/b7c0c09cfd137a1d1230e5748723766350bf1ab1/cloudinary.go#L83C2-L83C63)?  Are there other `AssetType`?
8. Could you please reset the repository and create a PR for the current files? I found there are many places that need to be optimized, it's hard to record them here.

### Reproduction Code (复现代码或截图)

No

**Comment by kkumar-gcc** [comment]
> Does AssetType must be set in [this line](https://github.com/goravel/cloudinary
/blob/b7c0c09cfd137a1d1230e5748723766350bf1ab1/cloudinary.go#L83C2-L83C63)? Are there other AssetType?

I couldn't find other method for it and `Assets` by default only get `image` assetType.

![image](https://github.com/goravel/cloudinary/assets/84431594/e7ebcd5a-2d86-4c3b-a73d-1291b6183812)
